version: '2.2'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    volumes:
      - jenkins_home:/var/jenkins_home:Z
    ports:
      - 8080:8080
    environment:
      DOCKER_HOST: "tcp://docker:2375"
    depends_on:
      - nexus
      - docker
    links:
      - nexus:nexus
      - docker:docker

  nexus:
    image: sonatype/nexus3:latest
    volumes:
      - nexus_data:/nexus-data:Z
    ports:
      - 8081:8081
      - 18443:18443

  docker:
    image: docker:dind
    privileged: true
    command: --insecure-registry=nexus:18443
    ports:
      - 2375:2375

volumes:
    jenkins_home:
    nexus_data:
